Python 3: use normal integers instead of long integers
Traceback (most recent call last):
  File "../../bin/compare-source-package-list", line 313
    for chunk in iter(lambda: f.read(128*64L), b''):
                                           ^
SyntaxError: invalid syntax