Python 3: write Planet Debian derivatives configs in text mode
Traceback (most recent call last):
  File "../../bin/derivative-to-planet-config", line 88, in <module>
    tmp.write(new_config)
  File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'