Python 3: use open() function instead of file() function
Traceback (most recent call last):
  File "../../bin/check-package-list", line 145, in <module>
    try: f = file(fn)
NameError: name 'file' is not defined